#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xc0,0xa8,0x00,0x13,0x1c,0xa5,
};

static const uint8_t chainparams_seed_test[] = {};

static const uint8_t chainparams_seed_testnet4[] = {};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
